// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function string(prim) {
  return prim;
}

function NotFound(Props) {
  return React.createElement("div", {
              style: {
                display: "flex",
                height: "100vh",
                width: "100%",
                alignItems: "center",
                justifyContent: "center"
              }
            }, React.createElement("span", {
                  style: {
                    display: "block",
                    fontSize: "2rem"
                  }
                }, "This page doesn't exist."));
}

var make = NotFound;

export {
  string ,
  make ,
}
/* react Not a pure module */
