// Generated by ReScript, PLEASE EDIT WITH CARE


function string(v) {
  return v;
}

function $$int(v) {
  return v;
}

var NumberOrString = {
  string: string,
  $$int: $$int
};

export {
  NumberOrString ,
}
/* No side effect */
