// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as GlassIcon from "./GlassIcon.js";
import * as ReactSelect from "react-select";
import ReactSelect$1 from "react-select";
import CountrySelectModuleCss from "./CountrySelect.module.css";

var styles = CountrySelectModuleCss;

var countries = [
  {
    label: "Afghanistan",
    value: "af"
  },
  {
    label: "Aland Islands",
    value: "ax"
  },
  {
    label: "Albania",
    value: "al"
  }
];

function makeValueContainer(props) {
  return React.createElement("div", {
              className: styles["value-container"]
            }, React.createElement(GlassIcon.make, {}), React.createElement(ReactSelect.components.ValueContainer, props));
}

function makeOption(props) {
  return React.createElement("div", {
              className: styles.option
            }, React.createElement(ReactSelect.components.Option, props, React.createElement("span", undefined, "flag"), React.cloneElement(React.createElement("span", undefined), props)));
}

var getComponents = {
  DropdownIndicator: null,
  ValueContainer: makeValueContainer,
  Option: makeOption
};

var Components = {
  makeValueContainer: makeValueContainer,
  makeOption: makeOption,
  getComponents: getComponents
};

function CountrySelect(Props) {
  return React.createElement(ReactSelect$1, {
              multi: false,
              options: countries,
              placeholder: "Select Country",
              components: getComponents
            });
}

var make = CountrySelect;

export {
  styles ,
  countries ,
  Components ,
  make ,
}
/* styles Not a pure module */
