// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Json$JsonCombinators from '@glennsl/rescript-json-combinators/src/Json.js';
import * as Json_Decode$JsonCombinators from '@glennsl/rescript-json-combinators/src/Json_Decode.js';

var countryJsonFile = Json_Decode$JsonCombinators.object(function (fields) {
  return {
    content: fields.required('content', Json_Decode$JsonCombinators.string),
  };
});

var files = Json_Decode$JsonCombinators.object(function (fields) {
  return {
    countryJsonFile: fields.required('counties.json', countryJsonFile),
  };
});

var gist = Json_Decode$JsonCombinators.object(function (fields) {
  return {
    files: fields.required('files', files),
  };
});

function decode(json) {
  return Json$JsonCombinators.decode(json, gist);
}

var GistDecoder = {
  countryJsonFile: countryJsonFile,
  files: files,
  gist: gist,
  decode: decode,
};

export { GistDecoder };
/* countryJsonFile Not a pure module */
