// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Json$JsonCombinators from '@glennsl/rescript-json-combinators/src/Json.js';
import * as Json_Decode$JsonCombinators from '@glennsl/rescript-json-combinators/src/Json_Decode.js';

var country = Json_Decode$JsonCombinators.object(function (fields) {
  return {
    label: fields.required('label', Json_Decode$JsonCombinators.string),
    value: fields.required('value', Json_Decode$JsonCombinators.string),
  };
});

var countries = Json_Decode$JsonCombinators.object(function (fields) {
  return {
    countries: fields.required(
      'countries',
      Json_Decode$JsonCombinators.array(country)
    ),
  };
});

function decode(json) {
  return Json$JsonCombinators.decode(json, countries);
}

var CountriesDecoder = {
  country: country,
  countries: countries,
  decode: decode,
};

export { CountriesDecoder };
/* country Not a pure module */
