// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function DownIcon(Props) {
  return React.createElement("svg", {
              height: "5px",
              width: "8px",
              version: "1.1",
              viewBox: "0 0 8 5",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("g", {
                  id: "Landing",
                  fill: "none",
                  fillRule: "evenodd",
                  stroke: "none",
                  strokeWidth: "1"
                }, React.createElement("g", {
                      id: "Artboard",
                      transform: "translate(-286.000000, -197.000000)"
                    }, React.createElement("g", {
                          id: "Group",
                          transform: "translate(185.000000, 186.000000)"
                        }, React.createElement("g", {
                              id: "Group",
                              transform: "translate(101.000000, 9.000000)"
                            }, React.createElement("rect", {
                                  id: "box",
                                  height: "8",
                                  width: "8",
                                  x: "0",
                                  y: "0"
                                }), React.createElement("polygon", {
                                  id: "icon",
                                  fill: "#333333",
                                  points: "0 2 8 2 4 7"
                                }))))));
}

var make = DownIcon;

export {
  make ,
}
/* react Not a pure module */
