// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Dropdown(Props) {
  var isOpen = Props.isOpen;
  var target = Props.target;
  var children = Props.children;
  var onClose = Props.onClose;
  var shadow = "hsla(218, 50%, 10%, 0.1)";
  var menuStyle = {
    backgroundColor: "white",
    height: "40px",
    marginTop: "4px",
    position: "absolute",
    zIndex: "2",
    borderRadius: "2px",
    boxShadow: "0 0 0 1px " + shadow + ", 0 4px 11px " + shadow + ""
  };
  var blanketStyle = {
    bottom: "0",
    left: "0",
    position: "fixed",
    right: "0",
    top: "0",
    zIndex: "1"
  };
  return React.createElement("div", {
              style: {
                position: "relative"
              }
            }, target, isOpen ? React.createElement("div", {
                    style: menuStyle
                  }, children) : null, isOpen ? React.createElement("div", {
                    style: blanketStyle,
                    onClick: (function (param) {
                        Curry._1(onClose, undefined);
                      })
                  }) : null);
}

var make = Dropdown;

export {
  make ,
}
/* react Not a pure module */
