// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Model from "../model/Model.js";
import * as React from "react";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as WebAPI from "../http/WebAPI.js";
import * as ViewModel from "../model/ViewModel.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var initialState_countries = [];

var initialState = {
  loading: false,
  error: "",
  countries: initialState_countries
};

function reducer(state, action) {
  if (typeof action === "number") {
    return {
            loading: true,
            error: "",
            countries: state.countries
          };
  } else if (action.TAG === /* Error */0) {
    return {
            loading: false,
            error: action._0,
            countries: state.countries
          };
  } else {
    return {
            loading: false,
            error: "",
            countries: action._0
          };
  }
}

function loadCountries(dispatch, signal) {
  var callback = function (result) {
    if (result.TAG !== /* Ok */0) {
      return Curry._1(dispatch, {
                  TAG: /* Error */0,
                  _0: "Unexpected error occured while reteriving countries data."
                });
    }
    var gist = Model.GistDecoder.decode(result._0);
    if (gist.TAG !== /* Ok */0) {
      return ;
    }
    try {
      var cjson = JSON.parse("{ \"countries\" : " + gist._0.files.countryJsonFile.content + " }");
      var data = ViewModel.CountriesDecoder.decode(cjson);
      if (data.TAG === /* Ok */0) {
        return Curry._1(dispatch, {
                    TAG: /* SuccessCountries */1,
                    _0: data._0.countries
                  });
      } else {
        return Curry._1(dispatch, {
                    TAG: /* Error */0,
                    _0: data._0
                  });
      }
    }
    catch (raw_obj){
      var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
      if (obj.RE_EXN_ID === Js_exn.$$Error) {
        var m = obj._1.message;
        if (m !== undefined) {
          return Curry._1(dispatch, {
                      TAG: /* Error */0,
                      _0: m
                    });
        } else {
          return ;
        }
      }
      throw obj;
    }
  };
  Curry._1(dispatch, /* Loading */0);
  WebAPI.getCountries("https://api.github.com/gists/659db3f4566df459bd59c8a53dc9f71f", callback, Caml_option.some(signal), undefined);
}

function useCountriesData(param) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  React.useEffect((function () {
          var controller = new AbortController();
          loadCountries(dispatch, controller.signal);
          return (function (param) {
                    controller.abort("Cancel the request");
                  });
        }), [dispatch]);
  return [
          state.loading,
          state.error,
          state.countries
        ];
}

export {
  initialState ,
  reducer ,
  loadCountries ,
  useCountriesData ,
}
/* Model Not a pure module */
