// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function string(v) {
  return v;
}

function $$int(v) {
  return v;
}

var NumberOrString = {
  string: string,
  $$int: $$int
};

function debounce(fn, delay) {
  var id = {
    contents: undefined
  };
  return function (param) {
    var tid = id.contents;
    if (tid !== undefined) {
      clearTimeout(Caml_option.valFromOption(tid));
    }
    id.contents = Caml_option.some(setTimeout((function (param) {
                Curry._1(fn, undefined);
              }), delay));
  };
}

export {
  NumberOrString ,
  debounce ,
}
/* No side effect */
