// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as NotFound from "../pages/not_found/NotFound.js";
import * as Js_promise from "rescript/lib/es6/js_promise.js";
import * as ErrorBoundary from "../components/error_boundary/ErrorBoundary.js";
import AppModuleCss from "./App.module.css";
import * as SuspensionLoader from "../components/suspension_loader/SuspensionLoader.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";

var styles = AppModuleCss;

function string(prim) {
  return prim;
}

function useState(prim) {
  return React.useState(function () {
              return Curry._1(prim, undefined);
            });
}

function App(Props) {
  var lazyHome = React.createElement(React.lazy(function (param) {
            var __x = import("../pages/home/Home.js");
            return Js_promise.then_((function (comp) {
                          return Promise.resolve({
                                      default: comp.make
                                    });
                        }), __x);
          }), undefined);
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var component = match ? React.createElement(NotFound.make, {}) : React.createElement(SuspensionLoader.make, {
          children: lazyHome
        });
  return React.createElement("main", {
              className: styles.main
            }, React.createElement(ErrorBoundary.make, {
                  children: React.createElement("div", {
                        className: styles["page-container"]
                      }, component)
                }));
}

var make = App;

export {
  styles ,
  string ,
  useState ,
  make ,
}
/* styles Not a pure module */
