// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function DownIcon(Props) {
  var className = Props.className;
  var tmp = {
    style: {
      backgroundColor: "transparent",
      border: "0",
      minHeight: "5px",
      minWidth: "8px",
      padding: "0",
      borderRadius: "0",
      boxShadow: "0 0 0 0 rgba(0, 0, 0, 0)"
    },
    height: "5px",
    width: "8px",
    version: "1.1",
    viewBox: "0 0 8 5",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  var tmp$1 = {
    id: "icon",
    points: "0 2 8 2 4 7"
  };
  if (className !== undefined) {
    tmp$1.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("g", {
                  id: "Landing",
                  fill: "none",
                  fillRule: "evenodd",
                  stroke: "none",
                  strokeWidth: "1"
                }, React.createElement("g", {
                      id: "Artboard",
                      transform: "translate(-286.000000, -197.000000)"
                    }, React.createElement("g", {
                          id: "Group",
                          transform: "translate(185.000000, 186.000000)"
                        }, React.createElement("g", {
                              id: "Group",
                              transform: "translate(101.000000, 9.000000)"
                            }, React.createElement("rect", {
                                  id: "box",
                                  height: "8",
                                  width: "8",
                                  x: "0",
                                  y: "0"
                                }), React.createElement("polygon", tmp$1))))));
}

var make = DownIcon;

export {
  make ,
}
/* react Not a pure module */
