// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from 'react';

function GlassIcon(Props) {
  return React.createElement(
    'svg',
    {
      height: '13px',
      width: '13px',
      version: '1.1',
      viewBox: '0 0 13 13',
      xmlns: 'http://www.w3.org/2000/svg',
    },
    React.createElement(
      'g',
      {
        id: 'Landing',
        fill: 'none',
        fillRule: 'evenodd',
        stroke: 'none',
        strokeWidth: '1',
      },
      React.createElement(
        'g',
        {
          id: 'Artboard',
          transform: 'translate(-196.000000, -226.000000)',
        },
        React.createElement(
          'g',
          {
            id: 'Group',
            transform: 'translate(185.000000, 186.000000)',
          },
          React.createElement(
            'g',
            {
              id: 'popup/popover/standard/text+search',
              transform: 'translate(0.000000, 29.000000)',
            },
            React.createElement(
              'g',
              {
                id: 'Group',
                transform: 'translate(10.000000, 10.000000)',
              },
              React.createElement('rect', {
                id: 'box',
                height: '14',
                width: '14',
                x: '0',
                y: '0',
              }),
              React.createElement('path', {
                id: 'icon',
                d: 'M6,1 C8.76142375,1 11,3.23857625 11,6 C11,7.01954236 10.6948479,7.96781264 10.1708943,8.75846025 L13.4700003,12.0600004 L12.0600004,13.4700003 L8.75846025,10.1708943 C7.96781264,10.6948479 7.01954236,11 6,11 C3.23857625,11 1,8.76142375 1,6 C1,3.23857625 3.23857625,1 6,1 Z M6,2.79999995 C4.23268877,2.79999995 2.79999995,4.23268877 2.79999995,6 C2.79999995,7.76731123 4.23268877,9.20000005 6,9.20000005 C7.76731123,9.20000005 9.20000005,7.76731123 9.20000005,6 C9.20000005,4.23268877 7.76731123,2.79999995 6,2.79999995 Z',
                fill: '#333333',
              })
            )
          )
        )
      )
    )
  );
}

var make = GlassIcon;

export { make };
/* react Not a pure module */
