// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./app/App.js";
import * as React from "react";
import * as Client from "react-dom/client";

import '../style/main.css'
;

var rootElm = document.querySelector("#root");

if (rootElm == null) {
  console.error("Failed to start React: couldn't find the #root element");
} else {
  var root = Client.createRoot(rootElm);
  root.render(React.createElement(React.StrictMode, {
            children: React.createElement(App.make, {})
          }));
}

export {
  
}
/*  Not a pure module */
