// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Loader from "../loader/Loader.js";

function SuspensionLoader(Props) {
  var children = Props.children;
  return React.createElement(React.Suspense, {
              fallback: React.createElement(Loader.make, {
                    className: "loading"
                  }),
              children: children
            });
}

var make = SuspensionLoader;

export {
  make ,
}
/* react Not a pure module */
